---
# cPanel Python Application Deployment Configuration
# Version: 1
# https://docs.cpanel.net/knowledge-base/web-services/guide-to-application-deployment/

deployment:
  tasks:
    # Pre-deployment tasks
    - export SETUPTOOLS_USE_DISTUTILS=stdlib
    - export PYTHONDONTWRITEBYTECODE=1
    
    # Upgrade pip
    - pip install --upgrade pip setuptools wheel
    
    # Install dependencies
    - pip install -r requirements.txt
    
    # Create necessary directories
    - mkdir -p logs
    - mkdir -p tmp
    
    # Set permissions
    - chmod 755 passenger_wsgi.py
    - chmod 644 .env
    
    # Post-deployment message
    - echo "PharmaFlow Solutions deployed successfully!"

